server:
  port: 8081

spring:
  application:
    name: springboot-api
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
